default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: zonawikii_development

test:
  <<: *default
  database: zonawikii_test

production:
  <<: *default
  database: zonawikii_production
