default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  host: <%= ENV['POSTGRES_HOST'] %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: zonawikii_development

test:
  <<: *default
  database: zonawikii_test

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: zonawikii_production
